### Name: Mathakari Shubham
### ID: AIS021

### Read data

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn

In [2]:
iris = sns.load_dataset("iris")

In [3]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

###  Dependent and Independent variable 

In [4]:
#independent variable
x = iris.iloc[:,0:4]
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [5]:
#dependent variable
y = iris.iloc[:,4]
y.head()

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

### Train test split

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x, y, train_size=0.80,test_size=0.20, random_state=100)


In [7]:
print("x_train shape: ",x_train.shape)
print("y_train shape: ",y_train.shape)
print("x_test shape:",x_test.shape)
print("y_test shape:",y_test.shape)

x_train shape:  (120, 4)
y_train shape:  (120,)
x_test shape: (30, 4)
y_test shape: (30,)


### Model import

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
knn = KNeighborsClassifier(n_neighbors=5)

### Model Fitting

In [10]:
knn.fit( x_train , y_train) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

### Model Prediction


In [11]:
y_pred = knn.predict(x_test)
print(y_pred)

['virginica' 'setosa' 'virginica' 'setosa' 'virginica' 'virginica'
 'setosa' 'setosa' 'virginica' 'setosa' 'setosa' 'virginica' 'setosa'
 'setosa' 'virginica' 'versicolor' 'versicolor' 'versicolor' 'virginica'
 'virginica' 'virginica' 'setosa' 'virginica' 'setosa' 'versicolor'
 'virginica' 'versicolor' 'setosa' 'versicolor' 'virginica']


###  confusion matrix

In [12]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[11  0  0]
 [ 0  6  0]
 [ 0  0 13]]


### accuracy 

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

1.0