# Download data Loan Prediction from Analytics Vidhya

### Predict Loan Eligibility for Dream Housing Finance company
Dream Housing Finance company deals in all kinds of home loans. They have presence across all urban, semi urban and rural areas. Customer first applies for home loan and after that company validates the customer eligibility for loan.

Company wants to automate the loan eligibility process (real time) based on customer detail provided while filling online application form. These details are Gender, Marital Status, Education, Number of Dependents, Income, Loan Amount, Credit History and others. To automate this process, they have provided a dataset to identify the customers segments that are eligible for loan amount so that they can specifically target these customers. 

# Train Model

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
loan = pd.read_csv("train_ctrUa4K.csv")

In [3]:
loan.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [6]:
loan1 = loan.copy()

In [7]:
loan1["Dependents"].mode()

0    0
dtype: object

In [8]:
loan1["Dependents"] = loan1["Dependents"].fillna(0)

In [9]:
loan1["Gender"] = loan1["Gender"].fillna('Male')

In [10]:
loan1["Married"].mode()

0    Yes
dtype: object

In [11]:
loan1["Married"] =  loan1["Married"].fillna('Yes')

In [12]:
loan1["Self_Employed"].mode()

0    No
dtype: object

In [13]:
loan1["Self_Employed"] = loan1["Self_Employed"].fillna('No')

In [14]:
loan1["LoanAmount"].mean()

146.41216216216216

In [15]:
loan1["LoanAmount"] = loan1["LoanAmount"].fillna(loan1["LoanAmount"].mean())

In [16]:
loan1["Loan_Amount_Term"].unique()

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  36.,  84.,  12.])

In [17]:
loan1["Loan_Amount_Term"].mode()

0    360.0
dtype: float64

In [18]:
loan1["Loan_Amount_Term"] = loan1["Loan_Amount_Term"].fillna(360)

In [19]:
loan1["Credit_History"].unique()

array([ 1.,  0., nan])

In [20]:
loan1["Credit_History"].mode()

0    1.0
dtype: float64

In [21]:
loan1["Credit_History"] = loan1["Credit_History"].fillna(1)

In [22]:
loan1["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [23]:
loan1["Dependents"].unique()

array(['0', '1', '2', '3+', 0], dtype=object)

In [24]:
from sklearn import preprocessing
l=["Gender","Married","Education","Self_Employed",]
for i in l:
    le = preprocessing.LabelEncoder()
    le.fit(loan1[i])
    loan1[i]= le.transform(loan1[i])
    

In [25]:
loan1 = pd.get_dummies(loan1, columns=['Dependents', 'Property_Area'])

In [26]:
loan1.head()

Loan_ID  Gender  Married  Education  Self_Employed  ApplicantIncome  \
0  LP001002       1        0          0              0             5849   
1  LP001003       1        1          0              0             4583   
2  LP001005       1        1          0              1             3000   
3  LP001006       1        1          1              0             2583   
4  LP001008       1        0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  146.412162             360.0             1.0   
1             1508.0  128.000000             360.0             1.0   
2                0.0   66.000000             360.0             1.0   
3             2358.0  120.000000             360.0             1.0   
4                0.0  141.000000             360.0             1.0   

  Loan_Status  Dependents_0  Dependents_0  Dependents_1  Dependents_2  \
0           Y             0             1             0             0   
1           N             0             0             1             0   
2           Y             0             1             0             0   
3           Y             0             1             0             0   
4           Y             0             1             0             0   

   Dependents_3+  Property_Area_Rural  Property_Area_Semiurban  \
0              0                    0                        0   
1              0                    1                        0   
2              0                    0                        0   
3              0                    0                        0   
4              0                    0                        0   

   Property_Area_Urban  
0                    1  
1                    0  
2                    1  
3                    1  
4                    1

### Spliting Data

In [41]:
X = loan1.drop(['Loan_ID', 'Loan_Status'], axis=1)
y = loan1['Loan_Status']

In [90]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.80,test_size=0.20, random_state=67) 

### Fitting Model

### Naive bayes

In [91]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 


In [117]:
gnb.fit(X_train, y_train)
y_pred=gnb.predict(X_test)
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
print("confusion matrix : \n",confusion_matrix(y_test, y_pred))

confusion matrix : 
 [[14 16]
 [ 8 85]]


In [118]:
print("Accuracy: \n",accuracy_score(y_test, y_pred))

Accuracy: 
 0.8048780487804879


In [119]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X_train, y_train)
y_pred1=mnb.predict(X_test)
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
print("confusion matrix : \n",confusion_matrix(y_test, y_pred1))

confusion matrix : 
 [[12 18]
 [50 43]]


In [120]:
print("Accuracy: \n",accuracy_score(y_test, y_pred1))

Accuracy: 
 0.44715447154471544


In [121]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(X_train, y_train)
y_pred2=bnb.predict(X_test)
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
print("confusion matrix : \n",confusion_matrix(y_test, y_pred2))
print("Accuracy: \n",accuracy_score(y_test, y_pred2))

confusion matrix : 
 [[15 15]
 [ 3 90]]
Accuracy: 
 0.8536585365853658


### Decision Tree

In [97]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf= clf.fit(X_train, y_train)

In [98]:
y_pred3 = clf.predict(X_test)

In [122]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("confusion matrix : \n",confusion_matrix(y_test, y_pred3))
print("Accuracy: \n",accuracy_score(y_test, y_pred3))

confusion matrix : 
 [[15 15]
 [ 3 90]]
Accuracy: 
 0.8536585365853658


### Random Forest

In [123]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200, random_state=67)
rf.fit(X_train, y_train)
y_pred4=rf.predict(X_test)

In [124]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("confusion matrix : \n",confusion_matrix(y_test, y_pred4))
print("Accuracy: \n",accuracy_score(y_test, y_pred4))

confusion matrix : 
 [[14 16]
 [ 6 87]]
Accuracy: 
 0.8211382113821138


### Voting Classifier

#### Hard Voting

In [129]:
from sklearn.ensemble import VotingClassifier
voting_clf_H = VotingClassifier(estimators=[('GNB', gnb), ('RF',rf), ('DT', clf),('BNB', bnb)], voting='hard')
voting_clf_H.fit(X_train, y_train)
y_pred5 =voting_clf_H.predict(X_test) 

In [130]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("confusion matrix : \n",confusion_matrix(y_test, y_pred5))
print("Accuracy: \n",accuracy_score(y_test, y_pred5))

confusion matrix : 
 [[15 15]
 [ 5 88]]
Accuracy: 
 0.8373983739837398


#### Soft voting

In [134]:
from sklearn.ensemble import VotingClassifier
voting_clf_S = VotingClassifier(estimators=[('GNB', gnb), ('RF',rf), ('DT', clf),('BNB', bnb)], voting='soft')
voting_clf_S.fit(X_train, y_train)
y_pred6 =voting_clf_S.predict(X_test) 

In [135]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("confusion matrix : \n",confusion_matrix(y_test, y_pred6))
print("Accuracy: \n",accuracy_score(y_test, y_pred6))

confusion matrix : 
 [[16 14]
 [ 3 90]]
Accuracy: 
 0.8617886178861789


# Test Data

In [136]:
loan2 = pd.read_csv('test_lAUu6dG.csv')

In [137]:
loan2.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [138]:
loan2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            367 non-null    object 
 1   Gender             356 non-null    object 
 2   Married            367 non-null    object 
 3   Dependents         357 non-null    object 
 4   Education          367 non-null    object 
 5   Self_Employed      344 non-null    object 
 6   ApplicantIncome    367 non-null    int64  
 7   CoapplicantIncome  367 non-null    int64  
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object 
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB


In [139]:
loan2["Gender"].mode()

0    Male
dtype: object

In [140]:
loan2["Gender"] = loan2["Gender"].fillna('Male')

In [141]:
loan2["Dependents"].mode()

0    0
dtype: object

In [142]:
loan2["Dependents"] = loan2["Dependents"].fillna(0)

In [143]:
loan2["Self_Employed"].mode()

0    No
dtype: object

In [144]:
loan2["Self_Employed"] = loan2["Self_Employed"].fillna('No')

In [145]:
loan2["LoanAmount"].mean()

136.13259668508286

In [146]:
loan2["LoanAmount"] = loan2["LoanAmount"].fillna(136.13259668508286)

In [147]:
loan1["Loan_Amount_Term"].mode()

0    360.0
dtype: float64

In [148]:
loan2["Loan_Amount_Term"] = loan2["Loan_Amount_Term"].fillna(360)

In [149]:
loan2["Credit_History"].mode()

0    1.0
dtype: float64

In [150]:
loan2["Credit_History"] = loan2["Credit_History"].fillna(1)

In [151]:
from sklearn import preprocessing
l=["Gender","Married","Education","Self_Employed",]
for i in l:
    le = preprocessing.LabelEncoder()
    le.fit(loan2[i])
    loan2[i]= le.transform(loan2[i])

In [152]:
loan2 = pd.get_dummies(loan2, columns=['Dependents', 'Property_Area'])

In [153]:
loan2.head()

Loan_ID  Gender  Married  Education  Self_Employed  ApplicantIncome  \
0  LP001015       1        1          0              0             5720   
1  LP001022       1        1          0              0             3076   
2  LP001031       1        1          0              0             5000   
3  LP001035       1        1          0              0             2340   
4  LP001051       1        0          1              0             3276   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0       110.0             360.0             1.0   
1               1500       126.0             360.0             1.0   
2               1800       208.0             360.0             1.0   
3               2546       100.0             360.0             1.0   
4                  0        78.0             360.0             1.0   

   Dependents_0  Dependents_0  Dependents_1  Dependents_2  Dependents_3+  \
0             0             1             0             0              0   
1             0             0             1             0              0   
2             0             0             0             1              0   
3             0             0             0             1              0   
4             0             1             0             0              0   

   Property_Area_Rural  Property_Area_Semiurban  Property_Area_Urban  
0                    0                        0                    1  
1                    0                        0                    1  
2                    0                        0                    1  
3                    0                        0                    1  
4                    0                        0                    1

In [154]:
X1 = loan2.drop('Loan_ID', axis=1)

In [155]:
from sklearn.ensemble import VotingClassifier
voting_clf_S = VotingClassifier(estimators=[('GNB', gnb), ('RF',rf), ('DT', clf),('BNB', bnb)], voting='soft')
voting_clf_S.fit(X_train, y_train)

VotingClassifier(estimators=[('GNB', GaussianNB()),
                             ('RF',
                              RandomForestClassifier(n_estimators=200,
                                                     random_state=67)),
                             ('DT', DecisionTreeClassifier()),
                             ('BNB', BernoulliNB())],
                 voting='soft')

In [156]:
y_pred7 =voting_clf_S.predict(X1) 

In [157]:
Loan_prediction = pd.read_csv('test_lAUu6dG.csv')

Loan_ID = Loan_prediction['Loan_ID']

In [158]:
submission=pd.DataFrame({'Loan_ID':Loan_ID, 'Loan_Status':y_pred7})
submission.to_csv("Loan Prediction.csv",index=False)