### Name: Mathakari Shubham
#### ID: AIS021

1. What is an array?

Ans: An array is a collection of items stored at contiguous memory locations. 

2. What is difference between array and list?

Ans:Arrays are great for numerical operations; lists cannot directly handle math operations.
     

3. How to change the shape of an array?

Ans:The reshape() function is used to give a new shape to an array without changing its data.

4. What does the name.strip () do?

Ans if we write  'name'.strip() it gives 'name'

5. When we use triple single or triple double quotes to define a string?

Ans: To create strings that span multiple lines, triple single quotes  or triple double quotes are used to enclose the string.

6. Create a character type array?

Ans:


In [18]:
import numpy as np
array = np.chararray(10)
array[:]=1
array

chararray([b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1'],
          dtype='|S1')

7. Create a “hello” string and access the string character "ll" in python?

Ans:

In [2]:
str1 = "hello"
print(str1[2:4])

ll


8. Create an array to get largest and smallest number using minimum and maximum function?

Ans:


In [7]:
import numpy as np
array1 = np.arange(10,150)
print('Largest number:',max(array1))
print('Smallest number:',min(array1))

Largest number: 149
Smallest number: 10


9. If name is “core python” then access the "python" from name and reverse "python" using slicing?

Ans:

In [50]:
name ="core python"
a = name[5:]
print('a:',name[5:])
print('b:',a[::-1])


a: python
b: nohtyp


10. Create an array of integer type and add element 12 using append method and remove one element using remove methods?

Ans:

In [9]:
array = np.array([10, 18, 8, 6, 30, 45])
array1 = np.append(array,12)
print('array1:',array1)
array2 = np.delete(array,4)
print('array2:',array2)



array1: [10 18  8  6 30 45 12]
array2: [10 18  8  6 45]


11. Create a single dimensional and 3 dimensional array using numpy?

Ans:
    

In [16]:
single_dimensional = np.array([10,7,17,18])
Three_dimensional = np.array([[[3, 2, 4], [1, 4, 6]], [[3, 5, 6], [9, 7, 8]]])
print('single_dimensional:',single_dimensional)
print('a:',Three_dimensional)

single_dimensional: [10  7 17 18]
a: [[[3 2 4]
  [1 4 6]]

 [[3 5 6]
  [9 7 8]]]


12. Create a “Programiz” string and convert the string into upper, lower case? And replace given string by “program” using replace method?

Ans:

In [24]:
string ="Programiz"
print('lower case:',string.lower())
print('upper case:',string.upper())

lower case: programiz
upper case: PROGRAMIZ


In [25]:
a =string.replace("Programiz","program")
print('a:',a)

a: program


13. Create a two array one using linspace and another using arange function and then subtract array1 from array 2?

Ans:

In [37]:
array1 =np.arange(1,11)
print('array1:',array1)
array2 =np.linspace(10,20,10)
print('array2:',array2)
sub =array2 - array1
print('sub:',sub)

array1: [ 1  2  3  4  5  6  7  8  9 10]
array2: [10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]
sub: [ 9.          9.11111111  9.22222222  9.33333333  9.44444444  9.55555556
  9.66666667  9.77777778  9.88888889 10.        ]


14. Create a “happy new year” string and then separate this string by (space) ",”?

Ans:

In [40]:
string ="happy new year"
spearated_string =string.split(", ")
print("spearated_string:",spearated_string)

spearated_string: ['happy new year']


15. Create two string and check whether one string present in another string using membership operator?

Ans:

In [58]:
import operator 
string1 = " is good boy"
string2 = "shekhar is good boy"
operator.contains(string2, string1)
 



True