In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## Data

In [48]:
hr = pd.read_csv('train_LZdllcl.csv')

In [49]:
hr.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [28]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   employee_id           54808 non-null  int64  
 1   department            54808 non-null  object 
 2   region                54808 non-null  object 
 3   education             52399 non-null  object 
 4   gender                54808 non-null  object 
 5   recruitment_channel   54808 non-null  object 
 6   no_of_trainings       54808 non-null  int64  
 7   age                   54808 non-null  int64  
 8   previous_year_rating  50684 non-null  float64
 9   length_of_service     54808 non-null  int64  
 10  KPIs_met >80%         54808 non-null  int64  
 11  awards_won?           54808 non-null  int64  
 12  avg_training_score    54808 non-null  int64  
 13  is_promoted           54808 non-null  int64  
dtypes: float64(1), int64(8), object(5)
memory usage: 5.9+ MB


In [29]:
hr = hr.dropna()

In [30]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(hr['gender'])
hr['gender']= le.transform(hr['gender'])

In [31]:
hr = pd.get_dummies(hr, columns=['department', 'education', 'recruitment_channel'])

In [32]:
X = hr.drop(['employee_id', 'region', 'is_promoted'], axis=1)
y = hr['is_promoted']

### Spliting Data

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=107)

In [34]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 
gnb.fit(X_train, y_train)
y_pred=gnb.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix
print('confusion_matrix:\n',confusion_matrix(y_test, y_pred))

confusion_matrix:
 [[12714   570]
 [ 1052   262]]


In [36]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8888888888888888


### Nearmiss

In [37]:
from imblearn.under_sampling import NearMiss
nr = NearMiss()
X_train_miss, y_train_miss = nr.fit_sample(X_train, y_train.ravel())

In [41]:
gnb.fit(X_train_miss, y_train_miss)
y_pred1=gnb.predict(X_test)

In [42]:
from sklearn.metrics import confusion_matrix
print('confusion_matrix:\n',confusion_matrix(y_test, y_pred1))

confusion_matrix:
 [[7292 5992]
 [ 673  641]]


In [43]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred1))

0.5434306069324565


### SMOTE

In [44]:
from imblearn.over_sampling import SMOTE
sm = SMOTE()
X_train_sm, y_train_sm = sm.fit_sample(X_train, y_train.ravel())

In [45]:
gnb.fit(X_train_sm, y_train_sm)
y_pred2=gnb.predict(X_test)

In [46]:
from sklearn.metrics import confusion_matrix
print('confusion_matrix:\n',confusion_matrix(y_test, y_pred2))

confusion_matrix:
 [[4277 9007]
 [ 204 1110]]


In [47]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred3))

0.42183860802849704
